services:
  - type: web
    name: quiz-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT intelligent_system_quiz:app
    plan: free